version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173" 
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "3000:3000" 
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/cookbook
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cookbook
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
