version: "3.8"

services:
  frontend:
    image: martblackcat/cookbook-frontend:latest
    container_name: cookbook-frontend
    
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    image: martblackcat/cookbook-backend:latest
    container_name: cookbook-backend
    
    ports:
      - "3000:3000"
    depends_on:
      - db

    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/cookbook

    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:latest
    container_name: cookbook-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cookbook
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: cookbook-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
